include:
  - project: telkomsel.com/pipeline-template-assets/website-pipeline-template
    ref: main
    file: lib-stages.yml
  - local: /.ci-compile.yml

variables:
  CI_PROJECT_NAME: "modal-base"
  PROJECT_DIR: "packages/components/molecules/modal-base"

compile:
  before_script:
    - cat ${NPMRC} > .npmrc
  script:
    - npm i --legacy-peer-deps && npm run build:modal-base

publish-jfrog:
  script:
    - npm run publish:modal-base
