include:
  - project: telkomsel.com/pipeline-template-assets/website-pipeline-template
    ref: main
    file: lib-stages.yml
  - local: /.ci-compile.yml

variables:
  CI_PROJECT_NAME: "spinner"
  PROJECT_DIR: "packages/components/atoms/spinner"

compile:
  before_script:
    - cat ${NPMRC} > .npmrc
  script:
    - npm i --legacy-peer-deps && npm run build:spinner

publish-jfrog:
  script:
    - npm run publish:spinner
